### ISSUE TITLE
Open Issues: test scope

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#26]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Scope should be the metadata only. Testing the data itself is very hard or practically impossible in many cases.

**Comment by cportele** [comment]
Agreed, the standardization target of the conformance class must be the data set metadata, not the data itself or the download services. It is ok to access a referenced resource to determine information, but then it needs to be specified how to access the resource in an automated test.

Assertions on the data set or the download service do not belong in this conformance class, these belong 
into the respective conformance classes for these standardization targets.

**Comment by cportele** [comment]
Proposed resolution:
- Update test cases to use a single standardization target per conformance class.

**Comment by cportele** [comment]
Proposed resolution:
- Update test cases to use a single standardization target per conformance class.

**Comment by aquaglia** [comment]
It seems unreasonable to download the full dataset every time the metadata is validated.
It is also practically valueless since by the time all the dataset has been validated, it might have changed and become invalid.
However, it is feasible and in general useful to "probe" and test only the first bytes/kilobytes/megabytes of a dataset. For xml this is enough to determine if the character encoding, the spatial object type, the encoding, the transfer rate and so on, correspond to what is declared and/or required.

**Comment by cportele** [comment]
Regarding "probing" see my comment in https://github.com/inspire-eu-validation/ats-metadata/issues/55

**Comment by aquaglia** [comment]
I also added some comments.

**Comment by cportele** [comment]
Resolution depends on resolution of #27

**Comment by cportele** [comment]
Resolution during [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10) - see #27:
- Implement the proposed change
