### ISSUE TITLE
All regulations on "Metadata for interoperability"...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#3]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

All regulations on "Metadata for interoperability" (see following issues) aim at datasets and series and only when applying to IR 1089/2010.
How to define that? Conformity statement citing IR 1089/2010 with pass= TRUE?
Or are these regulations relevant for all INSPIRE metadata regardless the level of fulfilling IR 1089/2010?

**Comment by cportele** [comment]
As they are part of 1089/2010 I assume this metadata conformance class is only relevant for metadata on datasets that conform to 1089/2010, i.e. are 'interoperable'. Only these metadata records have to conform and pass the tests. 

Whether a metadata record should pass the tests or not does not necessarily have to be derivable from the metadata record. Whether a WMS 1.3.0 implementation must meet the requirements of the INSPIRE WMS 1.3.0 conformance class - since it is the only "View Service"-capability on a spatial data set that is within the scope of INSPIRE - cannot be determined from just looking at the service.

Proposed resolution:
- no change (as no change is necessary)

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
